# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@4.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  linux:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:current-22.04
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run: |
          sudo apt -qq update
          sudo apt -yq install qt6-base-dev
      - run: mkdir -p ~/build-SMTPEmail
      - run: |
          PATH="/usr/lib/qt6/bin:$PATH"
          qmake src/SMTPEmail.pro -o ~/build-SMTPEmail/Makefile
          cd ~/build-SMTPEmail
          make
          rm -f .qmake.stash Makefile *.{cpp,h,o}
      - store_artifacts:
          path: ~/build-SMTPEmail
          destination: SmtpClient-for-Qt-linux
    working_directory: ~/project

  macos:
    macos:
      xcode: "12.5.1"
    steps:
      - checkout
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run: brew install qt
      - run: |
          qmake src/SMTPEmail.pro -o ~/build-SMTPEmail/Makefile
          cd ~/build-SMTPEmail
          make
          rm -f .qmake.stash Makefile *.{cpp,h,o}
      - store_artifacts:
          path: ~/build-SMTPEmail
          destination: SmtpClient-for-Qt-macos
    working_directory: ~/project

  windows:
    executor: win/default
    steps:
      - checkout
      - run: choco install qtcreator -y
      - run: |
          qmake src/SMTPEmail.pro -o ~/build-SMTPEmail/Makefile
          nmake
          rm -f .qmake.stash Makefile *.cpp *.h *.o
      - store_artifacts:
          path: ~/build-SMTPEmail
          destination: SmtpClient-for-Qt-win
    working_directory: ~/project

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  smtpclient-workflow:
    jobs:
      - linux
      - macos
      - windows
